name: Github Actions CI

on: [push]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12

      - run: npm ci
      - run: npm run lint
      - run: npm run htmllint
      - run: npm run stylelint

  build:
    needs: lint
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12

      - run: npm ci
      - run: npm run build
      - uses: actions/upload-artifact@v2
        with:
          name: my-build
          path: dist/*

  deploy:
    needs: build
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: my-build
          path: dist
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.S3_BUCKET_REGION }}

      - name: Remove Files
        run: aws s3 rm --recursive s3://${{ secrets.S3_BUCKET }}

      - name: Deploy
        run: aws s3 sync ./dist/masterarbeit-cog-openlayers s3://${{ secrets.S3_BUCKET }}